### PR TITLE
refactor: configuration for mustashe 

### LINKED ISSUE #27: Configuration option to set default for the `functional=` argument in `stash()`?
Would it be useful to be able to set the default for the `functional` argument in `stash("var", { ... }, functional = .default_functional)`? The implementation would be easy enough and based off of that for the 'here' integration. It seems like some people generally want it to be `TRUE` while others want the original default behavior with default `FALSE`. 

Thoughts @torfason?

### PR DESCRIPTION
**Pull request by jhrcook**
Add a single system for configuring global behavior and defaults for 'mustashe':

1. should the 'here' package be used for defining stashing file paths?
2. default value for `verbose` used in stashing functions
3. default value for `functional` used in stashing functions

Note that the first replaces the `use_here()` function.

### CODE REVIEW

**Comment by torfason** [comment]
Looks great. Three thoughts:

1. Would it be better to deprecate `use_here()` and `dont_use_here()`. Otherwise this little update would break existing scripts. But the implementation could be changed to simply use the new function.

2. `getOption()` supports the `default` parameter, which would make `mustache_use_here()` and friends much shorter, for example, that function would become:

```R
mustashe_use_here <- function() {
 getOption("mustashe.use_here", default=FALSE)
}
```

3. I do wonder (this is more of a question mark), if the function signature should be `mustache_config(..., use_here, functional, verbose)` to force people to name the parameters. It is great to include them as explicit parameters (supports findability of the options), but if people start calling it with `mustache_config(TRUE, FALSE, TRUE)` it leads to breakage if other settings were added later on (they would need to be added last, which might or might not be the most intuitive place). (Spoiler alert, I've actually been mulling over a new feature that would require an added option, I'll send you a message on that later :-)

**Comment by jhrcook** [comment]
All great ideas, I'll go ahead and add those in.

**Comment by torfason** [comment]
Awesome!

Extra n in "connfigure" in one of the tests (in tests/testthat/test-config_mustashe.R).

Other than that it looks good to go :-)

**Comment by torfason** [comment]
Booyah!

**Pull request merged**
