### PR TITLE
Utilize qs (quick serialization) R package instead of readr and RDS formats

### PR DESCRIPTION
**Pull request by jimbrig**
Hi @jhrcook,

Nice package! Glad I came across it - after much research on caching in R it seems like every other similar package gets unnecessarily over-complicated with R6, etc. Anyways, I implemented the package in a workflow for a client project and thought it would be worth sharing with you.

The only difference I made was utilizing the [qs](https://github.com/traversc/qs) package for stashing as opposed to readr and readRDS/saveRDS. 

I am also working on auto-detecting file names in the "code" argument to automatically apply a dependency on the last modified time of the data file. 

Let me know what you think!

Jimmy

### CODE REVIEW

**Comment by jhrcook** [comment]
Hey @jimbrig2011,

I'm glad you like the package, and thank you for contributing those changes. 

I think it is a great idea to use the 'qs' package for reading and writing. Originally, I had used 'readr' so that the tables with the hash values could be read easily (for diagnostic or fixing bugs, etc), but it really hasn't been necessary and they can still be read if needed by just importing them into R.

Is there a reason that you brought the `clear_stash()` and `unstash()` functions into `stash.R`?

Thank you,
Josh Cook

**Comment by jimbrig** [comment]
@jhrcook I didn't mean to move the functions. I changed it back in [this commit](https://github.com/jhrcook/mustashe/pull/4/commits/dc41024744379476db68ce45648c3890c2cfa615). Note that I should probably add a ".data" or ".qs" extension to the stashed files so that clear_stash does not remove all files like it currently does (I noticed in your test for clear_stash you had a ",txt" file not being deleted).

**Comment by jimbrig** [comment]
Also, any ideas on why the macOS devel check is not passing?

**Comment by jhrcook** [comment]
> @jhrcook I didn't mean to move the functions. I changed it back in [this commit](https://github.com/jhrcook/mustashe/pull/4/commits/dc41024744379476db68ce45648c3890c2cfa615). Note that I should probably add a ".data" or ".qs" extension to the stashed files so that clear_stash does not remove all files like it currently does (I noticed in your test for clear_stash you had a ",txt" file not being deleted).

Sorry, my bad on not realizing you moved `unstash()` and `clear_stash()` back. And yes, if you can add ".qs" as the extension for the data file, that would be great. The point of those tests and the restrictions on 'clear_stash()` is just to help prevent 'mustashe' from deleting files it didn't write. For that reason, can you reverse the changes to `clear_stash()` to check for the file extensions using `list.files(.stash_dir, full.names = TRUE, pattern = "qs$")` and `list.files(.stash_dir, full.names = TRUE, pattern = "hash$")`?

> Also, any ideas on why the macOS devel check is not passing?

I'm not sure why the Mac dev version doesn't pass, but it seems to be an issue with 'readr' and 'qs' installation. I have had the same problem with the 'readr' dependency in another package (['ggasym'](https://github.com/jhrcook/ggasym)). Anyway, since we are switching to 'qs' can you remove 'readr' as a dependency in the "DESCRIPTION" file? My guess is that 'qs' will still cause the test to fail, but I can live with that.

If you can take care of these changes, I think I should be able to merge your PR: 

- [ ] add the ".qs" extension to the data file names
- [ ] restore the pattern matching for `unstash()`
- [ ] uncomment the test that checks for the `other_file` (the one with a ".txt" extension
- [ ] remove 'readr' from the package dependencies

**Comment by jimbrig** [comment]
Sure thing I'll take care of those tonight or tomorrow. Preciate it.

**Comment by jhrcook** [comment]
It looks like the problem with dev versions of the test on Mac in caused by the spat between the developers of Tidyverse and Rcpp: https://community.rstudio.com/t/github-actions-failing-on-mac-devel-because-dplyr-and-tidyr-are-not-available/59343

> They are 'not available' because they failed to compile, see https://github.com/rabutler-usbr/knnstdisagg/runs/552880924#step:8:2460 . They failed to compile due to a bug in the CRAN version of Rcpp .
>
> Also the devel version of dplyr works because it no longer uses Rcpp.

**Comment by jhrcook** [comment]
Hey Jimmy, there was a bug that was causing problems on older versions of macOS that CRAN wants me to fix by 4/24. I was finally able to find someone with an old enough version to figure it out and fix it. Therefore, I would like to submit an updated version to CRAN in the next few days, and would really like to include the features you will add with this PR. If you have time, could you take care of the last few details, soon? I completely understand if you can't at the moment, and the new features can be included in a later update.

**Comment by jimbrig** [comment]
@jhrcook sorry man, gotten super swamped with work lately. I will try and get these changes done this afternoon. Thanks.

**Comment by jhrcook** [comment]
No worries, I completely understand.

**Comment by jimbrig** [comment]
- [x] add the ".qs" extension to the data file names
- [x] restore the pattern matching for unstash()
- [x] uncomment the test that checks for the other_file (the one with a ".txt" extension
- [x] remove 'readr' from the package dependencies

Notes: 
- I added myself to DESCRIPTION (feel free to remove)
- I did not increment package version
- I did not update cran comments nor NEWS

R CMD check results:
mustashe 0.1.1
Duration: 1m 8.7s
0 errors v | 0 warnings v | 0 notes v
R CMD check succeeded

**Comment by jimbrig** [comment]
@jhrcook Done, I also resolved the Merge Conflicts. Let me know if you need anything else.

I'll also add that for my implementation of this in a client project I made it so you could specify the directory to cache to via options(stash_dir = "path").

Also, see my forked repo's [Issue 2](https://github.com/jimbrig2011/mustashe/issues/2) and [Issue 3](https://github.com/jimbrig2011/mustashe/issues/3) for enhancements I am currently working on.

**Comment by jimbrig** [comment]
@jhrcook could you assign the PR to me so I receive notifications?

**Review by jhrcook — APPROVED** [review]

**Pull request merged**
